### ISSUE TITLE
tutoring registration flow related issues

### ISSUE THREAD

**Issue by katiebelleho** [omou-org/front-end#241]
# Design Ticket

**Designer:** Katie

**Issues:** 
Under Registration, Tutoring view 
- the cards should be Subjects created by the admin under the admin tab
- when you click on a Subject card, page should redirect to the 1x1 tutoring registration form with the subject pre-populated (see figma frames below)
- there also needs to be a review details section before they complete the registration. In this section, user is able to see the pre-determined total based on the subject, academic level and # of sessions input. User w/ access can also manually override the hourly rate here (please have Daniel confirm that we want this feature). 

![image](https://user-images.githubusercontent.com/60498283/73600955-5cadb200-450d-11ea-829a-55a28af4f428.png)
![image](https://user-images.githubusercontent.com/60498283/73600996-20c71c80-450e-11ea-8186-39a0c6bc9c32.png)
![image](https://user-images.githubusercontent.com/60498283/73601003-3b999100-450e-11ea-959b-a7f594cf7222.png)

**Comment by NeilAllavarpu** [comment]
Are subjects the same thing as course categories?

**Comment by katiebelleho** [comment]
> Are subjects the same thing as course categories?

Yes (e.g. math, chemistry, etc). Subjects are created primarily to categorize tutoring sessions, the items on screenshot 1 look like they are class names.

**Comment by NeilAllavarpu** [comment]
@katiebelleho screenshots of fixes
<img width="1280" alt="Captura de Pantalla 2020-02-26 a la(s) 22 26 04" src="https://user-images.githubusercontent.com/13577797/75417939-16b6f480-58e7-11ea-9379-4e6303649ea3.png">
<img width="1280" alt="Captura de Pantalla 2020-02-26 a la(s) 22 24 23" src="https://user-images.githubusercontent.com/13577797/75417936-1585c780-58e7-11ea-8e2f-4d4bb2118e44.png">
<img width="1280" alt="Captura de Pantalla 2020-02-26 a la(s) 22 23 53" src="https://user-images.githubusercontent.com/13577797/75417933-13bc0400-58e7-11ea-9cb8-b06a5d0447d3.png">

**Comment by katiebelleho** [comment]
@NeilAllavarpu 

Registration Catelog (Tutoring) - looks great!


Registration form - can we divide the sections as below?
![image](https://user-images.githubusercontent.com/60498283/75419697-48ca5580-58eb-11ea-8536-d99ae9cf7d64.png)

Price Tool - 
![image](https://user-images.githubusercontent.com/60498283/75419849-98108600-58eb-11ea-95a2-af5e4f0a68b8.png)

**Comment by dhuangg** [comment]
@katiebelleho that "whats dis" is me lol. basically on the tech side it's not easy to update all of the fields so that the duration, sessions, category, and academic level match up with the previous fields in the case that the user. The quick solution to this would be to delete the fields from the previous sections, and only have this be the one source to set the category, grade level, duration, and number of sessions.

**Comment by dhuangg** [comment]
@katiebelleho  are you sure selecting for the course before the student makes sense? I think from a flow perspective, it's helpful that the user has to first select for the student so that they would be able to validate if the course they're selecting makes sense/prevents mistakes.

For example, if Jimmy is in 4th grade who wants to attend an "Intro to Computer" course, it would be helpful for the user to see that they've selected "Jimmy" who they know is in 4th grade, then "Intro to Computers," compared to if the user first selects for the course (which they may select "AP Computer Science" or something) then selecting Jimmy without noticing the mistake.

Let me know your thoughts.

**Comment by dhuangg** [comment]
@katiebelleho as a compromise, since the true technical fix to this is complicated and won't be done in time, I've removed the other fields so that the Tuition Price Quote tool sets these fields and you won't see these fields in the other sections. There's also a checkmark that will animate to green when you've confirmed the fields.

[Link to gif of animated checkmark](https://media.giphy.com/media/TgaU7MdY7g3PbuKNKD/giphy.gif)
